name: HungerGames
main: HungerGames\HungerGames
version: 1.0.0
api: 
- 3.0.0
- 2.0.0

commands:
    hg:
        usage: /hg
        description: HungerGames-Commands
    setrank:
        usage: /setrank
        description: Rank-Commands